Importing libraries

In [7]:
import pandas as pd
import numpy as np
import keras_tuner as kt
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import importlib
from tensorflow.keras.callbacks import EarlyStopping 
import os

Load process the data

In [55]:
# Files locations
animal_names = pd.read_csv(os.path.join("data", "animal_names.csv"))
image_folders = os.listdir(os.path.join("data", "animals", "animals"))
number_images = len(image_folders)
files_locations = os.path.join("data", "animals/")

# Create a list of full paths by joining the base path with each image folder
folder_paths = [os.path.join(files_locations, image) for image in image_folders]

# Create the DataFrame with animal names and corresponding folder paths
image_ls = [image for image in image_folders]
animal_names_ls = [animal for animal in animal_names.iloc[:, 0].values]

#ensure all animals list is in image ls
# Create a DataFrame to store matching animals and their folders
matching_animals = []
for animal in sorted(animal_names_ls):
    for image in sorted(image_ls):
        if animal == image:
            matching_animals.append({"animal": animal, "folder": os.path.join(files_locations, image)})

# Create DataFrame from matching animals if any were found
if matching_animals:
    animal_dt_frame = pd.DataFrame(matching_animals)
    display(animal_dt_frame.head(90))

        animal                   folder
0       badger      data/animals/badger
1          bat         data/animals/bat
2         bear        data/animals/bear
3          bee         data/animals/bee
4       beetle      data/animals/beetle
..         ...                      ...
84       whale       data/animals/whale
85        wolf        data/animals/wolf
86      wombat      data/animals/wombat
87  woodpecker  data/animals/woodpecker
88       zebra       data/animals/zebra

[89 rows x 2 columns]

In [58]:
animal_dt_frame.head(90)

# see the list of files in the folder
print(os.listdir(os.path.join("data", "animals", "animals", "badger")))

['648af59ce9.jpg', '2aac5ffd72.jpg', '0836f4eb45.jpg', '6f6978e81e.jpg', '89a8316cd4.jpg', '0c29e0107f.jpg', '7eebcfe7f7.jpg', '77bbc33783.jpg', '2a242797a3.jpg', '028efe8aab.jpg', '8d46358cff.jpg', '70ad9eb57e.jpg', '86e99c22bc.jpg', '00f56e5c92.jpg', '315c444990.jpg', '37a4e3ef89.jpg', '14d27983c0.jpg', '285fa8e668.jpg', '0e13bf2bf3.jpg', '23bfad16a7.jpg', '87d1db4af3.jpg', '30c66e7ad1.jpg', '2e5a00c0a5.jpg', '3cf13ad980.jpg', '047c50963a.jpg', '5c5d9cb086.jpg', '474f28df0a.jpg', '1f06d5b24c.jpg', '4e04eaba81.jpg', '7f3de940fe.jpg', '3e9f67e828.jpg', '63ecc10a24.jpg', '4c273d12a9.jpg', '59a092f934.jpg', '860fea93aa.jpg', '630f6e0af4.jpg', '51f50a9015.jpg', '6b36a20a5a.jpg', '26edf44cd9.jpg', '5bffbd51cf.jpg', '4c2236afb5.jpg', '6e0e5b7cdf.jpg', '63d7c3e6d0.jpg', '21ec1b1f1a.jpg', '0798f04ce0.jpg', '147a5daad3.jpg', '1ca97cd058.jpg', '10a6d3492c.jpg', '0cf04d0dab.jpg', '68f189620f.jpg', '010fce8ee7.jpg', '06b48e099f.jpg', '68d85c376b.jpg', '173fedc818.jpg', '2a8b186a9d.jpg', '2c8396c663.jpg', '378aa5cc58.jpg', '4b889c5467.jpg', '709f331442.jpg', '99e296bf48.jpg']

In [68]:
# process the data for each animal in the folders see the total of images and the number of animals
total_animal = len(animal_names_ls)
print("Found", total_animal, "animals")
total_images = len(image_folders)
print("Found", total_images, "images")



#for each folder of the animals see the total of images
for animal in animal_dt_frame["animal"]:
    total_images_per_animal = len(os.listdir(os.path.join("data", "animals", "animals", animal)))
    print(f"Found {total_images_per_animal} images for {animal}")

#save the animal_dt_frame to a csv file
animal_dt_frame.to_csv(os.path.join("data", "animal_dt_frame.csv"), index=False)

#load the animal_dt_frame from a csv file
animal_dt_frame = pd.read_csv(os.path.join("data", "animal_dt_frame.csv"))
animal_dt_frame.head(10)

Found 89 animals
Found 90 images
Found 60 images for badger
Found 60 images for bat
Found 60 images for bear
Found 60 images for bee
Found 60 images for beetle
Found 60 images for bison
Found 60 images for boar
Found 60 images for butterfly
Found 60 images for cat
Found 60 images for caterpillar
Found 60 images for chimpanzee
Found 60 images for cockroach
Found 60 images for cow
Found 60 images for coyote
Found 60 images for crab
Found 60 images for crow
Found 60 images for deer
Found 60 images for dog
Found 60 images for dolphin
Found 60 images for donkey
Found 60 images for dragonfly
Found 60 images for duck
Found 60 images for eagle
Found 60 images for elephant
Found 60 images for flamingo
Found 60 images for fly
Found 60 images for fox
Found 60 images for goat
Found 60 images for goldfish
Found 60 images for goose
Found 60 images for gorilla
Found 60 images for grasshopper
Found 60 images for hamster
Found 60 images for hare
Found 60 images for hedgehog
Found 60 images for hippopotamus
Found 60 images for hornbill
Found 60 images for horse
Found 60 images for hummingbird
Found 60 images for hyena
Found 60 images for jellyfish
Found 60 images for kangaroo
Found 60 images for koala
Found 60 images for ladybugs
Found 60 images for leopard
Found 60 images for lion
Found 60 images for lizard
Found 60 images for lobster
Found 60 images for mosquito
Found 60 images for moth
Found 60 images for mouse
Found 60 images for octopus
Found 60 images for okapi
Found 60 images for orangutan
Found 60 images for otter
Found 60 images for owl
Found 60 images for ox
Found 60 images for oyster
Found 60 images for panda
Found 60 images for parrot
Found 60 images for pelecaniformes
Found 60 images for penguin
Found 60 images for pig
Found 60 images for pigeon
Found 60 images for porcupine
Found 60 images for possum
Found 60 images for raccoon
Found 60 images for rat
Found 60 images for reindeer
Found 60 images for rhinoceros
Found 60 images for sandpiper
Found 60 images for seahorse
Found 60 images for seal
Found 60 images for shark
Found 60 images for sheep
Found 60 images for snake
Found 60 images for sparrow
Found 60 images for squid
Found 60 images for squirrel
Found 60 images for starfish
Found 60 images for swan
Found 60 images for tiger
Found 60 images for turkey
Found 60 images for turtle
Found 60 images for whale
Found 60 images for wolf
Found 60 images for wombat
Found 60 images for woodpecker
Found 60 images for zebra

        animal                    folder
0       badger       data/animals/badger
1          bat          data/animals/bat
2         bear         data/animals/bear
3          bee          data/animals/bee
4       beetle       data/animals/beetle
5        bison        data/animals/bison
6         boar         data/animals/boar
7    butterfly    data/animals/butterfly
8          cat          data/animals/cat
9  caterpillar  data/animals/caterpillar

hyberband model

In [ ]:
tuner = kt.Hyperband(
    fn.build_cnn_model,
    objective="val_accuracy",
    max_epochs=20,
    factor=3,
    directory="hyperband",
    project_name="corn_tuning_2",
)
tuner.search(train, epochs=10, validation_data=test)